<?php
/**
 * IncomingDocumentApi
 * PHP version 8.1
 *
 * @category Class
 * @package  cbeyersdorf\easybill
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * easybill REST API
 *
 * The first version of the easybill REST API. [CHANGELOG](https://api.easybill.de/rest/v1/CHANGELOG.md)  ## Authentication  You can choose between two available methods: `Basic Auth` or `Bearer Token`.  In each HTTP request, one of the following HTTP headers is required:  ``` # Basic Auth Authorization: Basic base64_encode('<email>:<api_key>') # Bearer Token Authorization: Bearer <api_key> ```  ## Limitations  ### Request Limit  * PLUS: 10 requests per minute * BUSINESS: 60 requests per minute  If the limit is exceeded, you will receive the HTTP error: `429 Too Many Requests`  ### Result Limit  All result lists are limited to 100 by default. This limit can be increased by the query parameter `limit` to a maximum of 1000.  ## Query filter  Many list resources can be filtered. In `/documents` you can filter e.g. by number with `/documents?number=111028654`. If you want to filter multiple numbers, you can either enter them separated by commas `/documents?number=111028654,222006895` or as an array `/documents?number[]=111028654&number[]=222006895`.  **Warning**: The maximum size of an HTTP request line in bytes is 4094. If this limit is exceeded, you will receive the HTTP error: `414 Request-URI Too Large`  ### Escape commas in query  You can escape commans in query `name=Patrick\\, Peter` if you submit the header `X-Easybill-Escape: true` in your request.  ## Property login_id  This is the login of your admin or employee account.  ## Date and Date-Time format Please use the timezone `Europe/Berlin`. * **date** = *Y-m-d* = `2016-12-31` * **date-time** = *Y-m-d H:i:s* = `2016-12-31 03:13:37`  Date or datetime can be `null` because the attributes have been added later and the entry is older.
 *
 * The version of the OpenAPI document: 1.100.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace cbeyersdorf\easybill\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use cbeyersdorf\easybill\ApiException;
use cbeyersdorf\easybill\Configuration;
use cbeyersdorf\easybill\FormDataProcessor;
use cbeyersdorf\easybill\HeaderSelector;
use cbeyersdorf\easybill\ObjectSerializer;

/**
 * IncomingDocumentApi Class Doc Comment
 *
 * @category Class
 * @package  cbeyersdorf\easybill
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class IncomingDocumentApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'incomingDocumentsGet' => [
            'application/json',
        ],
        'incomingDocumentsIdFilesFileIdDownloadGet' => [
            'application/json',
        ],
        'incomingDocumentsIdFilesGet' => [
            'application/json',
        ],
        'incomingDocumentsIdGet' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation incomingDocumentsGet
     *
     * Fetch incoming documents list
     *
     * @param  int|null $limit Limited the result. Default is 100. Maximum can be 1000. (optional)
     * @param  int|null $page Set current Page. Default is 1. (optional)
     * @param  string|null $sort Sort direction for created_at. Default is ASC. (optional, default to 'ASC')
     * @param  string|null $created_at Filter incoming documents by created_at. You can filter one date with created_at&#x3D;2024-01-15, an exact date-time with created_at&#x3D;2024-01-15 10:30:00 or between like 2024-01-01,2024-12-31. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['incomingDocumentsGet'] to see the possible values for this operation
     *
     * @throws \cbeyersdorf\easybill\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \cbeyersdorf\easybill\Model\IncomingDocuments
     */
    public function incomingDocumentsGet($limit = null, $page = null, $sort = 'ASC', $created_at = null, string $contentType = self::contentTypes['incomingDocumentsGet'][0])
    {
        list($response) = $this->incomingDocumentsGetWithHttpInfo($limit, $page, $sort, $created_at, $contentType);
        return $response;
    }

    /**
     * Operation incomingDocumentsGetWithHttpInfo
     *
     * Fetch incoming documents list
     *
     * @param  int|null $limit Limited the result. Default is 100. Maximum can be 1000. (optional)
     * @param  int|null $page Set current Page. Default is 1. (optional)
     * @param  string|null $sort Sort direction for created_at. Default is ASC. (optional, default to 'ASC')
     * @param  string|null $created_at Filter incoming documents by created_at. You can filter one date with created_at&#x3D;2024-01-15, an exact date-time with created_at&#x3D;2024-01-15 10:30:00 or between like 2024-01-01,2024-12-31. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['incomingDocumentsGet'] to see the possible values for this operation
     *
     * @throws \cbeyersdorf\easybill\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \cbeyersdorf\easybill\Model\IncomingDocuments, HTTP status code, HTTP response headers (array of strings)
     */
    public function incomingDocumentsGetWithHttpInfo($limit = null, $page = null, $sort = 'ASC', $created_at = null, string $contentType = self::contentTypes['incomingDocumentsGet'][0])
    {
        $request = $this->incomingDocumentsGetRequest($limit, $page, $sort, $created_at, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\cbeyersdorf\easybill\Model\IncomingDocuments',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\cbeyersdorf\easybill\Model\IncomingDocuments',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\cbeyersdorf\easybill\Model\IncomingDocuments',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation incomingDocumentsGetAsync
     *
     * Fetch incoming documents list
     *
     * @param  int|null $limit Limited the result. Default is 100. Maximum can be 1000. (optional)
     * @param  int|null $page Set current Page. Default is 1. (optional)
     * @param  string|null $sort Sort direction for created_at. Default is ASC. (optional, default to 'ASC')
     * @param  string|null $created_at Filter incoming documents by created_at. You can filter one date with created_at&#x3D;2024-01-15, an exact date-time with created_at&#x3D;2024-01-15 10:30:00 or between like 2024-01-01,2024-12-31. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['incomingDocumentsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function incomingDocumentsGetAsync($limit = null, $page = null, $sort = 'ASC', $created_at = null, string $contentType = self::contentTypes['incomingDocumentsGet'][0])
    {
        return $this->incomingDocumentsGetAsyncWithHttpInfo($limit, $page, $sort, $created_at, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation incomingDocumentsGetAsyncWithHttpInfo
     *
     * Fetch incoming documents list
     *
     * @param  int|null $limit Limited the result. Default is 100. Maximum can be 1000. (optional)
     * @param  int|null $page Set current Page. Default is 1. (optional)
     * @param  string|null $sort Sort direction for created_at. Default is ASC. (optional, default to 'ASC')
     * @param  string|null $created_at Filter incoming documents by created_at. You can filter one date with created_at&#x3D;2024-01-15, an exact date-time with created_at&#x3D;2024-01-15 10:30:00 or between like 2024-01-01,2024-12-31. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['incomingDocumentsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function incomingDocumentsGetAsyncWithHttpInfo($limit = null, $page = null, $sort = 'ASC', $created_at = null, string $contentType = self::contentTypes['incomingDocumentsGet'][0])
    {
        $returnType = '\cbeyersdorf\easybill\Model\IncomingDocuments';
        $request = $this->incomingDocumentsGetRequest($limit, $page, $sort, $created_at, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'incomingDocumentsGet'
     *
     * @param  int|null $limit Limited the result. Default is 100. Maximum can be 1000. (optional)
     * @param  int|null $page Set current Page. Default is 1. (optional)
     * @param  string|null $sort Sort direction for created_at. Default is ASC. (optional, default to 'ASC')
     * @param  string|null $created_at Filter incoming documents by created_at. You can filter one date with created_at&#x3D;2024-01-15, an exact date-time with created_at&#x3D;2024-01-15 10:30:00 or between like 2024-01-01,2024-12-31. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['incomingDocumentsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function incomingDocumentsGetRequest($limit = null, $page = null, $sort = 'ASC', $created_at = null, string $contentType = self::contentTypes['incomingDocumentsGet'][0])
    {

        if ($limit !== null && $limit > 1000) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling IncomingDocumentApi.incomingDocumentsGet, must be smaller than or equal to 1000.');
        }
        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling IncomingDocumentApi.incomingDocumentsGet, must be bigger than or equal to 1.');
        }
        
        if ($page !== null && $page < 1) {
            throw new \InvalidArgumentException('invalid value for "$page" when calling IncomingDocumentApi.incomingDocumentsGet, must be bigger than or equal to 1.');
        }
        



        $resourcePath = '/incoming-documents';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sort,
            'sort', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $created_at,
            'created_at', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation incomingDocumentsIdFilesFileIdDownloadGet
     *
     * Download a file attached to an incoming document
     *
     * @param  string $id UUID of the incoming document (required)
     * @param  string $file_id UUID of the file (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['incomingDocumentsIdFilesFileIdDownloadGet'] to see the possible values for this operation
     *
     * @throws \cbeyersdorf\easybill\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \SplFileObject
     */
    public function incomingDocumentsIdFilesFileIdDownloadGet($id, $file_id, string $contentType = self::contentTypes['incomingDocumentsIdFilesFileIdDownloadGet'][0])
    {
        list($response) = $this->incomingDocumentsIdFilesFileIdDownloadGetWithHttpInfo($id, $file_id, $contentType);
        return $response;
    }

    /**
     * Operation incomingDocumentsIdFilesFileIdDownloadGetWithHttpInfo
     *
     * Download a file attached to an incoming document
     *
     * @param  string $id UUID of the incoming document (required)
     * @param  string $file_id UUID of the file (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['incomingDocumentsIdFilesFileIdDownloadGet'] to see the possible values for this operation
     *
     * @throws \cbeyersdorf\easybill\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \SplFileObject, HTTP status code, HTTP response headers (array of strings)
     */
    public function incomingDocumentsIdFilesFileIdDownloadGetWithHttpInfo($id, $file_id, string $contentType = self::contentTypes['incomingDocumentsIdFilesFileIdDownloadGet'][0])
    {
        $request = $this->incomingDocumentsIdFilesFileIdDownloadGetRequest($id, $file_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\SplFileObject',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\SplFileObject',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SplFileObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation incomingDocumentsIdFilesFileIdDownloadGetAsync
     *
     * Download a file attached to an incoming document
     *
     * @param  string $id UUID of the incoming document (required)
     * @param  string $file_id UUID of the file (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['incomingDocumentsIdFilesFileIdDownloadGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function incomingDocumentsIdFilesFileIdDownloadGetAsync($id, $file_id, string $contentType = self::contentTypes['incomingDocumentsIdFilesFileIdDownloadGet'][0])
    {
        return $this->incomingDocumentsIdFilesFileIdDownloadGetAsyncWithHttpInfo($id, $file_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation incomingDocumentsIdFilesFileIdDownloadGetAsyncWithHttpInfo
     *
     * Download a file attached to an incoming document
     *
     * @param  string $id UUID of the incoming document (required)
     * @param  string $file_id UUID of the file (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['incomingDocumentsIdFilesFileIdDownloadGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function incomingDocumentsIdFilesFileIdDownloadGetAsyncWithHttpInfo($id, $file_id, string $contentType = self::contentTypes['incomingDocumentsIdFilesFileIdDownloadGet'][0])
    {
        $returnType = '\SplFileObject';
        $request = $this->incomingDocumentsIdFilesFileIdDownloadGetRequest($id, $file_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'incomingDocumentsIdFilesFileIdDownloadGet'
     *
     * @param  string $id UUID of the incoming document (required)
     * @param  string $file_id UUID of the file (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['incomingDocumentsIdFilesFileIdDownloadGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function incomingDocumentsIdFilesFileIdDownloadGetRequest($id, $file_id, string $contentType = self::contentTypes['incomingDocumentsIdFilesFileIdDownloadGet'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling incomingDocumentsIdFilesFileIdDownloadGet'
            );
        }

        // verify the required parameter 'file_id' is set
        if ($file_id === null || (is_array($file_id) && count($file_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $file_id when calling incomingDocumentsIdFilesFileIdDownloadGet'
            );
        }


        $resourcePath = '/incoming-documents/{id}/files/{fileId}/download';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{id}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }
        // path params
        if ($file_id !== null) {
            $resourcePath = str_replace(
                '{fileId}',
                ObjectSerializer::toPathValue($file_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/octet-stream', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation incomingDocumentsIdFilesGet
     *
     * Fetch files list for an incoming document
     *
     * @param  string $id UUID of the incoming document (required)
     * @param  int|null $limit Limited the result. Default is 100. Maximum can be 1000. (optional)
     * @param  int|null $page Set current Page. Default is 1. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['incomingDocumentsIdFilesGet'] to see the possible values for this operation
     *
     * @throws \cbeyersdorf\easybill\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \cbeyersdorf\easybill\Model\IncomingDocumentFiles
     */
    public function incomingDocumentsIdFilesGet($id, $limit = null, $page = null, string $contentType = self::contentTypes['incomingDocumentsIdFilesGet'][0])
    {
        list($response) = $this->incomingDocumentsIdFilesGetWithHttpInfo($id, $limit, $page, $contentType);
        return $response;
    }

    /**
     * Operation incomingDocumentsIdFilesGetWithHttpInfo
     *
     * Fetch files list for an incoming document
     *
     * @param  string $id UUID of the incoming document (required)
     * @param  int|null $limit Limited the result. Default is 100. Maximum can be 1000. (optional)
     * @param  int|null $page Set current Page. Default is 1. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['incomingDocumentsIdFilesGet'] to see the possible values for this operation
     *
     * @throws \cbeyersdorf\easybill\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \cbeyersdorf\easybill\Model\IncomingDocumentFiles, HTTP status code, HTTP response headers (array of strings)
     */
    public function incomingDocumentsIdFilesGetWithHttpInfo($id, $limit = null, $page = null, string $contentType = self::contentTypes['incomingDocumentsIdFilesGet'][0])
    {
        $request = $this->incomingDocumentsIdFilesGetRequest($id, $limit, $page, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\cbeyersdorf\easybill\Model\IncomingDocumentFiles',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\cbeyersdorf\easybill\Model\IncomingDocumentFiles',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\cbeyersdorf\easybill\Model\IncomingDocumentFiles',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation incomingDocumentsIdFilesGetAsync
     *
     * Fetch files list for an incoming document
     *
     * @param  string $id UUID of the incoming document (required)
     * @param  int|null $limit Limited the result. Default is 100. Maximum can be 1000. (optional)
     * @param  int|null $page Set current Page. Default is 1. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['incomingDocumentsIdFilesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function incomingDocumentsIdFilesGetAsync($id, $limit = null, $page = null, string $contentType = self::contentTypes['incomingDocumentsIdFilesGet'][0])
    {
        return $this->incomingDocumentsIdFilesGetAsyncWithHttpInfo($id, $limit, $page, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation incomingDocumentsIdFilesGetAsyncWithHttpInfo
     *
     * Fetch files list for an incoming document
     *
     * @param  string $id UUID of the incoming document (required)
     * @param  int|null $limit Limited the result. Default is 100. Maximum can be 1000. (optional)
     * @param  int|null $page Set current Page. Default is 1. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['incomingDocumentsIdFilesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function incomingDocumentsIdFilesGetAsyncWithHttpInfo($id, $limit = null, $page = null, string $contentType = self::contentTypes['incomingDocumentsIdFilesGet'][0])
    {
        $returnType = '\cbeyersdorf\easybill\Model\IncomingDocumentFiles';
        $request = $this->incomingDocumentsIdFilesGetRequest($id, $limit, $page, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'incomingDocumentsIdFilesGet'
     *
     * @param  string $id UUID of the incoming document (required)
     * @param  int|null $limit Limited the result. Default is 100. Maximum can be 1000. (optional)
     * @param  int|null $page Set current Page. Default is 1. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['incomingDocumentsIdFilesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function incomingDocumentsIdFilesGetRequest($id, $limit = null, $page = null, string $contentType = self::contentTypes['incomingDocumentsIdFilesGet'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling incomingDocumentsIdFilesGet'
            );
        }

        if ($limit !== null && $limit > 1000) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling IncomingDocumentApi.incomingDocumentsIdFilesGet, must be smaller than or equal to 1000.');
        }
        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling IncomingDocumentApi.incomingDocumentsIdFilesGet, must be bigger than or equal to 1.');
        }
        
        if ($page !== null && $page < 1) {
            throw new \InvalidArgumentException('invalid value for "$page" when calling IncomingDocumentApi.incomingDocumentsIdFilesGet, must be bigger than or equal to 1.');
        }
        

        $resourcePath = '/incoming-documents/{id}/files';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);


        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{id}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation incomingDocumentsIdGet
     *
     * Fetch incoming document
     *
     * @param  string $id UUID of the incoming document (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['incomingDocumentsIdGet'] to see the possible values for this operation
     *
     * @throws \cbeyersdorf\easybill\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \cbeyersdorf\easybill\Model\IncomingDocument
     */
    public function incomingDocumentsIdGet($id, string $contentType = self::contentTypes['incomingDocumentsIdGet'][0])
    {
        list($response) = $this->incomingDocumentsIdGetWithHttpInfo($id, $contentType);
        return $response;
    }

    /**
     * Operation incomingDocumentsIdGetWithHttpInfo
     *
     * Fetch incoming document
     *
     * @param  string $id UUID of the incoming document (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['incomingDocumentsIdGet'] to see the possible values for this operation
     *
     * @throws \cbeyersdorf\easybill\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \cbeyersdorf\easybill\Model\IncomingDocument, HTTP status code, HTTP response headers (array of strings)
     */
    public function incomingDocumentsIdGetWithHttpInfo($id, string $contentType = self::contentTypes['incomingDocumentsIdGet'][0])
    {
        $request = $this->incomingDocumentsIdGetRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\cbeyersdorf\easybill\Model\IncomingDocument',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\cbeyersdorf\easybill\Model\IncomingDocument',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\cbeyersdorf\easybill\Model\IncomingDocument',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation incomingDocumentsIdGetAsync
     *
     * Fetch incoming document
     *
     * @param  string $id UUID of the incoming document (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['incomingDocumentsIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function incomingDocumentsIdGetAsync($id, string $contentType = self::contentTypes['incomingDocumentsIdGet'][0])
    {
        return $this->incomingDocumentsIdGetAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation incomingDocumentsIdGetAsyncWithHttpInfo
     *
     * Fetch incoming document
     *
     * @param  string $id UUID of the incoming document (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['incomingDocumentsIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function incomingDocumentsIdGetAsyncWithHttpInfo($id, string $contentType = self::contentTypes['incomingDocumentsIdGet'][0])
    {
        $returnType = '\cbeyersdorf\easybill\Model\IncomingDocument';
        $request = $this->incomingDocumentsIdGetRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'incomingDocumentsIdGet'
     *
     * @param  string $id UUID of the incoming document (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['incomingDocumentsIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function incomingDocumentsIdGetRequest($id, string $contentType = self::contentTypes['incomingDocumentsIdGet'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling incomingDocumentsIdGet'
            );
        }


        $resourcePath = '/incoming-documents/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{id}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
